services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: es-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false          # disable auth
      - xpack.security.http.ssl.enabled=false # disable https
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  es_data:
    driver: local
